### ISSUE TITLE
When repo is empty/no commits, synchronization with Github fails (UX problem?)

### ISSUE THREAD

**Issue by Connoropolous** [noflo/noflo-ui#936] opened 2020-02-19 23:14 UTC
Steps to reproduce:
- Create a Project
- Add an empty Github Repository through the Project Settings, with 0 commits
- Hit 'Synchronize'
- Error

Platform: MacOS
Browser: Firefox

I expect due to changes in Github APIs
<img width="1541" alt="Screen Shot 2020-02-19 at 5 53 13 PM" src="https://user-images.githubusercontent.com/1409121/74885633-0e3d4780-5344-11ea-9f22-80856af18589.png">

<img width="1561" alt="Screen Shot 2020-02-19 at 5 54 10 PM" src="https://user-images.githubusercontent.com/1409121/74884429-28c1f180-5341-11ea-9e04-4882984006d1.png">

**Update: doesn't occur (and functions as expected) if there has been AT LEAST one commit to the repo**
https://github.com/noflo/noflo-ui/issues/936#issuecomment-588531628

**Comment by Connoropolous** [comment] 2020-02-19 23:36
I am checking around, and looks like the rough dependency tree here is:

- noflo-ui
  - [noflo-github](https://github.com/noflo/noflo-github)
    - [octo](https://github.com/bergie/octo)
      - [Githubs V3 API](http://labratrevenge.com/octo/) & http://developer.github.com/v3

I wonder which action specifically produces this

**Comment by Connoropolous** [comment] 2020-02-19 23:39
Hm, the response is a 409 which "indicates a request conflict with current state of the server."
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

**Comment by Connoropolous** [comment] 2020-02-19 23:40
Oh! The issue doesn't appear, if I first add a single commit to the empty repo

**Comment by Connoropolous** [comment] 2020-02-19 23:42
I would now consider this a mere UX issue :)

**Comment by bergie** [comment] 2020-09-03 18:33
Duplicate of #500

**Closed by bergie** 2020-09-03 18:33 UTC
