### ISSUE TITLE
lost an entire graph permanently by installing noflo-flow

### ISSUE THREAD

**Issue by ryedin** [noflo/noflo-ui#449] opened 2015-02-27 04:48 UTC
This one hit me hard.

Had a substantial graph I was working on. I hadn't recently downloaded it as JSON to save to disk because, hey, localStorage autosaving is convenient and noflo-ui would never just up and lose an entire graph, right?

I installed noflo-flow and restarted my nodejs runtime, then refreshed the page. I got a bunch of "ArrayPort has no method isAddressable" errors immediately, and my graph didn't load. The mini-map looked right, but no graph nodes in the main area, just blackness.

I then stopped the runtime, uninstalled noflo-flow and restarted. I refreshed again and now my graph is gone forever.

There is an issue logged over in that project as well, but noflo-ui should never lose a graph like this, no matter what kind of errors occur during startup.

I just learned an important lesson about this project. You can lose hours of work if you're not careful.

**Comment by bergie** [comment] 2015-02-27 15:42
This sounds curious. I simply can't see how changing something on a runtime would affect a graph. The way we do runtime communications in noflo-ui, graph changes flow only from the client to the runtime, not the other way around.

But if for some reason the graph got modified, there should still be the graph journal history kept separately of the graph itself, and hence you should be able to get to the previous state by clicking the *undo* button in the bottom-right corner of the UI.

However, whatever we do... since we're keeping your projects only in the browser IndexedDB and not on our servers (for obvious privacy reasons your code never goes through our hands), we're not 100% secure against the browser storage somehow bombing out, and will never be. This is exactly why we have support for GitHub synchronization. While browser storage is reasonably stable, the only real way to keep your code secure is pushing to a real version control system.

It would be useful to see what happened with your IndexedDB (did it get corrupted, was there a transaction that cleared the graph and which could be undone, etc). If you're interested in debugging those with me, let me know. And in the case the worst happened, I'm deeply sorry. Since the data is kept on the client machine, there is unfortunately only so much we can do...

**Comment by ryedin** [comment] 2015-02-27 15:59
Thanks, Henri. Unfortunately I think it's too late on this one. I did try clicking the undo button, to no affect (of potential interest to you is that I wasn't 100% positive that was an undo button until you just confirmed it). After several refreshes I gave up and deleted the graph, thinking it was somehow corrupted. Also, I'm not using flowhub but a local install of noflo-ui, so my backup routine is using the 'download' button on each graph (which I'll be doing much more regularly now). -- once I get more into the codebases one of the first things I plan to contribute is a 'local git repo' feature.

At any rate, the exact operations were as follows...

1. installed noflo-flow and restarted the runtime
2. on refresh of the ui, got the ArrayPort errors via the desktop notifications
3. created a new graph called 'test' in order to make a playground to see if I could maybe still use some of the noflow-flow components even though I got those odd errors
4. made a little graph and tried to run it... no luck
5. navigated back to my main working graph to see if it would run
6. the main area was black while the mini-map was normal
7. refreshed the page to see if that would help
8. main are black and now mini-map was also black
9. tears

**Comment by ryedin** [comment] 2015-02-27 16:09
BTW, I really appreciate the offer to debug. If I hadn't deleted the graph I'd take you up on it. 

I may have a little time later to try to reproduce the behavior. If I do I'll post details here.

**Comment by forresto** [comment] 2015-02-27 16:14
This doesn't help other than to rule out one factor: I have noticed a bug where the-graph-thumb won't refresh with an empty graph. (Just found the [source of the bug](https://github.com/the-grid/the-graph/blob/6c24c553c08b2415e18e691fc4a57f94fef62ab0/the-graph-thumb/the-graph-thumb.html#L108-L110).)

**Comment by ryedin** [comment] 2015-02-27 16:32
and FWIW, re-creating the graph took substantially less time this morning (and it looks a lot cleaner than the first time), which speaks to the power of this way of doing things (I don't want you guys to think all I do is complain :))

**Comment by jonnor** [comment] 2015-11-22 21:16
Closing since we don't have enough info to reproduce. If someone sees similar, please comment + reopen!

**Closed by jonnor** 2015-11-22 21:16 UTC
