### ISSUE TITLE
Colors on runtime selection panel are difficult to read

### ISSUE THREAD

**Issue by automata** [noflo/noflo-ui#441] opened 2015-02-07 20:01 UTC
At least for a color blind like me, it's not so easy to read the `runtime name` and `address`. White as font color is a good alternative.

![captura de tela 2015-02-07 as 09 57 56](https://cloud.githubusercontent.com/assets/49062/6093738/42b62dbc-aeb0-11e4-9b0a-21fac14ab898.png)

**Comment by forresto** [comment] 2015-02-09 21:59
Tests WCAG accessibility guidelines: http://jxnblk.com/colorable/

**Comment by bergie** [comment] 2015-02-10 00:49
Dupe of #438

**Closed by bergie** 2015-02-10 00:49 UTC
Labels: ux
