### ISSUE TITLE
Windows: Grunt build fails because Webpack cannot find modules

### ISSUE THREAD

**Issue by robs15** [noflo/noflo-ui#595] opened 2016-07-05 09:56 UTC
Hi all,
    Task "noflo_browser" throws issues relating to dependency files not found, starting with "root/fbp.json" not found. Am not able to figure out, why. Any help would be appreciated.

Thanks,
Robi.

**Comment by bergie** [comment] 2016-07-05 12:58
Have you done `npm install` recently? The components are now installed via NPM instead of component.io

**Comment by robs15** [comment] 2016-07-05 13:13
Yes, this is, as of today.

**Comment by jonnor** [comment] 2016-07-05 13:36
Please post the log of the build run, including the command you ran. Otherwise it is impossible to help.

**Comment by robs15** [comment] 2016-07-06 08:28
This is what I did after cloning the rep. Mine is Win 7, 64bit. Attached is the output log.
1) npm install
2) grunt build
[gruntLog.docx](https://github.com/noflo/noflo-ui/files/349358/gruntLog.docx)

Regards.

**Comment by bergie** [comment] 2016-07-06 13:08
Hmm, it sounds like Windows compatibility with webpack might be the issue here

**Comment by jonnor** [comment] 2016-07-06 13:31
Yes, the build is fine on Travis CI as of some minutes ago.

**Comment by jonnor** [comment] 2016-07-06 13:34
Or it could be an NPM versjon issue. Must use NPM v 3+, and should use nodejs 4+

@robs15 which `npm --version` do you have?

**Comment by robs15** [comment] 2016-07-06 14:00
2.15.1

**Comment by jonnor** [comment] 2016-07-06 14:53
Did you wipe `node_modules` and `npm install` again after updating to NPM 3?

**Comment by robs15** [comment] 2016-07-07 02:25
No I didn't. But will try & check if that helps. Thanks!

**Comment by robs15** [comment] 2016-07-07 02:52
Deleted the old folder, did a clone again. Same situation. Gets stuck at the point, searching for fbp.json.

**Comment by aretecode** [comment] 2016-07-07 02:54
@robs15 did you try running `./node_modules/noflo/bin/noflo-cache-preheat`?

**Comment by jonnor** [comment] 2016-07-19 12:26
^ above might be the problem

**Comment by xcapt** [comment] 2016-08-28 14:17
Hi there,
Was the above solved for @robs15 ? I am stuck at the same point.

@aretecode: I am unsure what to do from running ./node_modules/noflo/bin/noflo-cache-preheat
So still on Windows: running node ./node_modules/noflo/bin/noflo-cache-preheat

I get the following error message:

Any clue ?

noflo-ui\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

ReferenceError: document is not defined
  at module.exports (D:\src\noflo-ui\node_modules\noflo-polymer\lib\ComponentLoader.coffee:15:14)
  at ComponentLoader.registerLoader (D:\src\noflo-ui\node_modules\noflo\lib\ComponentLoader.js:247:14)
  at D:\src\noflo-ui\node_modules\noflo\lib\loader\NodeJs.js:52:23
  at Array.forEach (native)
  at registerModules (D:\src\noflo-ui\node_modules\noflo\lib\loader\NodeJs.js:48:29)
  at D:\src\noflo-ui\node_modules\noflo\lib\loader\NodeJs.js:132:18
  at tryCatcher (D:\src\noflo-ui\node_modules\bluebird\js\release\util.js:16:23)
  at Promise.successAdapter [as _fulfillmentHandler0] (D:\src\noflo-ui\node_modules\bluebird\js\release\nodeify.js:23:30)
...

**Comment by aretecode** [comment] 2016-08-28 19:57
An easy way to get it working is using a Virtual Machine running some linux flavour.

**Comment by xcapt** [comment] 2016-09-15 18:23
we sponsored a dev to get to the root cause of the issue

windows build is fixed with this PR

https://github.com/noflo/grunt-noflo-browser/pull/9

**Comment by jonnor** [comment] 2016-09-15 20:35
Fix is in master now. Thank you!

**Closed** 2016-09-15 20:34 UTC

**Comment by robs15** [comment] 2016-09-16 06:40
Thanks all for the efforts !
