### ISSUE TITLE
stub component ui

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#241] opened 2014-05-20 20:53 UTC
_(issue branched from #214)_

"New Component" at top of library list. Then dialog to define name and space-separated list of inports and outports.

This could then generate the boilerplate for the code view.

---

The workaround for now is to make new CoffeeScript component that just defines the ports:

```
noflo = require 'noflo'

exports.getComponent = ->
  c = new noflo.Component
  c.inPorts.add 'in'
  c.inPorts.add 'in2'
  c.inPorts.add 'in3'
  c.outPorts.add 'out'
  return c
```

**Comment by bergie** [comment] 2018-03-29 10:43
Dupe of #266

**Closed by bergie** 2018-03-29 10:43 UTC
Labels: enhancement
