### ISSUE TITLE
Allow dynamic URL scheme to also register projects

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#359] opened 2014-09-18 01:01 UTC
Should be possible to have a URL similar what is used for runtime "live mode" for projects. It should then sync the project down from github, same as when you manually enter the details.

This could be used by projects in their README.md files "Open in Flowhub".
Eventually it should be possible to fork the github repo directly from the UI.

**Comment by bergie** [comment] 2017-05-03 20:58
Dupe of #638

**Closed by bergie** 2017-05-03 20:58 UTC
Labels: enhancement
