### ISSUE TITLE
notification popups lack context

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#467] opened 2015-03-30 14:16 UTC
![screenshot from 2015-03-30 16 10 20](https://cloud.githubusercontent.com/assets/1279486/6898046/d6f13ebc-d6f7-11e4-9e14-0b02557eaeb6.png)

All I did was selecting a runtime for a graph that is stored in the browser. I'll did the source of the exceptions and try to at least add some context. For the scope of this report I wonder if we could do better. These notifications are not actionable for the user (or what am I supposed to do now, besides closing them).

**Comment by bergie** [comment] 2017-11-10 22:54
Dupe of #399

**Closed by bergie** 2017-11-10 22:54 UTC
Labels: bug, debugging, ux
